version: 2

models:
  - name: stg_clients
    description: "Clients avec types de données convertis et doublons gérés"
    columns:
      - name: id
        description: "Identifiant unique du client"
        tests:
          - unique
          - not_null
      - name: name
        description: "Nom du client"
      - name: job
        description: "Métier du client"
      - name: email
        description: "Adresse email du client"
      - name: account_id
        description: "Numéro de carte de fidélité"

  - name: stg_stores
    description: "Magasins avec coordonnées GPS séparées"
    columns:
      - name: id
        description: "Identifiant unique du magasin"
        tests:
          - unique
          - not_null
      - name: latlng
        description: "Coordonnées GPS brutes"
      - name: latitude
        description: "Latitude du magasin"
      - name: longitude
        description: "Longitude du magasin"
      - name: opening
        description: "Heure d'ouverture"
      - name: closing
        description: "Heure de fermeture"
      - name: type
        description: "Type de magasin"

  - name: stg_products
    description: "Produits avec types de données convertis"
    columns:
      - name: id
        description: "Identifiant unique du produit"
        tests:
          - unique
          - not_null
      - name: ean
        description: "Code EAN du produit"
      - name: brand
        description: "Marque du produit"
      - name: description
        description: "Description du produit"

  - name: stg_transactions
    description: "Transactions avec timestamp, account_id et gestion des doublons"
    columns:
      - name: transaction_id
        description: "Identifiant unique de la transaction"
        tests:
          - unique
          - not_null
      - name: client_id
        description: "Identifiant du client"
        tests:
          - not_null
      - name: date
        description: "Date de la transaction"
      - name: hour
        description: "Heure de la transaction"
      - name: minute
        description: "Minute de la transaction"
      - name: product_id
        description: "Identifiant du produit"
        tests:
          - not_null
      - name: quantity
        description: "Quantité achetée"
      - name: store_id
        description: "Identifiant du magasin"
        tests:
          - not_null
      - name: transaction_timestamp
        description: "Horodatage complet de la transaction"
        tests:
          - not_null
      - name: account_id
        description: "Numéro de carte de fidélité du client"
      - name: is_orphan_store
        description: "Indique si le magasin n'existe pas dans la dimension stores"
